version: '3.3'
services: 
  php:
    build:
      context: ./Dockerfiles/ 
      dockerfile: Dockerfile-php
    networks:
      - word
    volumes:
      - ./www/:/var/html/www/

  nginx:
    image: nginx:1.15
    restart: always
    networks:
      - word
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        #- /etc/letsencrypt/:/etc/letsencrypt/
      - ./www/:/var/html/www/
    ports:
      - "80:80"
      - "443:443"

  mysql:
    image: mysql:5.7.24
    networks:
      - word
    volumes:
      - ./db/db_data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d 
    restart: always
    env_file:
      - .env/db.env

networks:
  word:
